#
# Build: docker build -t apt-cacher .
# Run: docker run -d -p 3142:3142 --name apt-cacher-run apt-cacher
#
# and then you can run containers with:
#   docker run -t -i --rm -e http_proxy http://dockerhost:3142/ debian bash
#
FROM ubuntu:14.04
MAINTAINER SvenDowideit@docker.com
ENV DEBIAN_FRONTEND noninteractive

VOLUME ["/var/cache/apt-cacher-ng"]
RUN apt-get -qq update && apt-get -qq install apt-cacher-ng
RUN chmod a+rwx /var/cache/apt-cacher-ng

EXPOSE 3142
CMD /usr/sbin/apt-cacher-ng ForeGround=1 Port=3142
