FROM ubuntu:trusty
MAINTAINER Michael Koval <mkoval@cs.cmu.edu>
ENV DEBIAN_FRONTEND noninteractive

COPY internal-setup.sh internal-build.sh internal-distro.py internal-wstool.sh view-results.py view-all-results.sh /
RUN ./internal-setup.sh

CMD tail -f /var/log/dmesg
