FROM ubuntu:14.04
MAINTAINER Michael Koval <mkoval@cs.cmu.edu>
ENV DEBIAN_FRONTEND noninteractive

# Create non-root user 'ubuntu' with sudo access.
RUN groupadd ubuntu
RUN useradd -g ubuntu -G sudo ubuntu
RUN echo ubuntu:u | chpasswd
RUN cp -a /etc/skel /home/ubuntu
RUN chown -R ubuntu:ubuntu /home/ubuntu
RUN echo "ubuntu ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/ubuntu

# Set up Perl locales to avoid tons of warnings.
RUN apt-get -qq update && apt-get -qq install locales
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN locale-gen

# Set environment variable that wstool and rosdep expect.
# TODO: Template ROS_DISTRO
ENV TERM xterm
ENV SHELL /bin/bash
ENV LANG en_US.UTF-8
ENV LANGUAGE=en_US
ENV LC_ALL en_US.UTF-8
ENV ROS_DISTRO indigo

# Install bare-bones system utilities.
RUN apt-get -qq update && apt-get -qq install python-pip wget git mercurial subversion wget

# Add the PR APT repository.
RUN echo "deb http://packages.personalrobotics.ri.cmu.edu:8765/public $(lsb_release -sc) main" > /etc/apt/sources.list.d/pr.list
COPY pr.key pr.key
RUN apt-key add pr.key

# Add ROS APT repository.
RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros.list
RUN wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
RUN apt-key add ros.key

## Install ROS. Also initialize rosdep, which is only
## necessary once immediately after installation. 
RUN apt-get -qq update && apt-get -qq install ros-${ROS_DISTRO}-ros-base python-catkin-tools python-rosdep python-wstool
RUN rosdep init

# Setup eatmydata to speed up Apt installation.
RUN apt-get -qq install eatmydata

# Setup apt-cacher-ng to cache Apt packages.
RUN echo 'Acquire::http { Proxy "http://aptcacherng:3142"; };' >> /etc/apt/apt.conf.d/01proxy
#COPY sources.list /etc/apt/sources.list
#COPY ros.list /etc/apt/sources.list.d/ros.list

## Manually install OpenRAVE (this is a hack).
## TODO: Install OpenRAVE from a .deb package.
#WORKDIR /home/ubuntu/src
#RUN wstool set -y openrave https://github.com/personalrobotics/openrave.git --git
#RUN wstool update openrave
#RUN wget -P openrave/ https://gist.githubusercontent.com/mkoval/495b40fe828a727987e2/raw/539e5c92babb89ac543cdac49c5276b48d59af8c/package.xml

# Create a workspace.
COPY build-rosinstall.sh build-rosinstall.sh

#CMD ./build-rosinstall.sh
CMD tail -f /var/log/dmesg
