FROM ubuntu:14.04
MAINTAINER Michael Koval <mkoval@cs.cmu.edu>
ENV DEBIAN_FRONTEND noninteractive

# Create non-root user 'ubuntu' with sudo access.
RUN groupadd ubuntu
RUN useradd -g ubuntu -G sudo ubuntu
RUN echo ubuntu:u | chpasswd
RUN cp -a /etc/skel /home/ubuntu
RUN chown -R ubuntu:ubuntu /home/ubuntu
RUN echo "ubuntu ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/ubuntu

# Set up Perl locales to avoid tons of warnings.
RUN apt-get -qq update && apt-get -qq install locales
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN locale-gen

# Set environment variable that wstool and rosdep expect.
# TODO: Template the OS version and ROS_DISTRO.
ENV TERM xterm
ENV SHELL /bin/bash
ENV LANG en_US.UTF-8
ENV LANGUAGE=en_US
ENV LC_ALL en_US.UTF-8
ENV ROS_DISTRO indigo

# Install bare-bones system utilities.
RUN apt-get -qq update && apt-get -qq install eatmydata python-pip wget git mercurial subversion wget

# Add the PR APT repository.
# TODO: We should download 'pr.key' from a server, just like we do for ROS.
RUN echo "deb http://packages.personalrobotics.ri.cmu.edu:8765/public $(lsb_release -sc) main" > /etc/apt/sources.list.d/pr.list
COPY pr.key pr.key
RUN apt-key add pr.key

# Add ROS APT repository.
RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros.list
RUN wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
RUN apt-key add ros.key

# Install ROS.
RUN apt-get -qq update && eatmydata apt-get -qq install ros-${ROS_DISTRO}-ros-base python-catkin-tools python-rosdep python-wstool

# Initialize rosdep, including our custom rosdep keys.
RUN rosdep init
RUN wget -P /etc/ros/rosdep/sources.list.d https://raw.githubusercontent.com/personalrobotics/pr-rosinstalls/master/rosdep/10-pr.list

# Cache Apt packages using apt-cacher-ng.
RUN echo 'Acquire::http { Proxy "http://apt-cacher-ng:3142"; };' >> /etc/apt/apt.conf.d/01proxy

# Copy the test script into the Docker container.
COPY run-internal.sh run-internal.sh

CMD tail -f /var/log/dmesg
